"""Project-wide constants for Learn2Slither."""

BOARD_SIZE = 10
INITIAL_SNAKE_LENGTH = 3

ACTIONS = ("UP", "DOWN", "LEFT", "RIGHT")

MOVES = {
    "UP": (-1, 0),
    "DOWN": (1, 0),
    "LEFT": (0, -1),
    "RIGHT": (0, 1),
}

SYMBOL_WALL = "W"
SYMBOL_HEAD = "H"
SYMBOL_BODY = "S"
SYMBOL_GREEN = "G"
SYMBOL_RED = "R"
SYMBOL_EMPTY = "0"

REWARD_GREEN_APPLE = 10
REWARD_RED_APPLE = -10
REWARD_MOVE = -1
REWARD_GAME_OVER = -50

ALPHA = 0.1
GAMMA = 0.9
EPSILON_START = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY = 0.995

CELL_PX = 40
DEFAULT_SPEED = 10.0

MAX_STEPS_PER_SESSION = 2000
